[package]
name = "axiom-db"
version = "0.1.5"
edition = "2021"
description = "Official CLI for AxiomDB — manage projects, branches, secrets and monitoring from your terminal "
license = "MIT"
homepage = "https://github.com/squareexp/axiom-db"
repository = "https://github.com/squareexp/axiom-db"
keywords = ["axiom", "database", "cli", "postgres", "devtools","self-hosted-db"]
categories = ["command-line-utilities", "database"]

[[bin]]
name = "axiom"
path = "src/main.rs"

[dependencies]
# CLI parsing
clap = { version = "4", features = ["derive", "color", "wrap_help"] }

# Async runtime
tokio = { version = "1", features = ["full"] }

# HTTP
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "rustls-tls"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Errors
anyhow = "1"
thiserror = "1"

# Terminal UI
dialoguer = { version = "0.11", features = ["password"] }
indicatif = "0.17"
colored = "2"
comfy-table = "7"

# Config storage
dirs = "5"

# Time
chrono = { version = "0.4", features = ["serde"] }

# UUID
uuid = { version = "1", features = ["v4"] }

# SSE streaming
futures-util = "0.3"
bytes = "1"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true
